### ISSUE TITLE
Out of memory when using Text 2 Image

### ISSUE THREAD

**Issue by johnpaulbin** [THUDM/CogView#14]
`[Wed Jun 16 19:21:01 2021] Memory cgroup out of memory: Killed process 15052 (python3) total-vm:19700460kB, anon-rss:11917232kB, file-rss:89696kB, shmem-rss:12288kB, UID:0 pgtables:25896kB oom_score_adj:0`

Is what I can get after the process has been killed.
Is there a way to optimize this to run on a GPU with lower ram? I'm using a Tesla T4 on Google Colab.

Thanks.

**Comment by johnpaulbin** [comment]
I'm using `--max-inference-batch-size 1` BTW with no success.

**Comment by jp-krow** [comment]
Update: V100 with 25 GB:
`RuntimeError: CUDA out of memory. Tried to allocate 7.47 GiB (GPU 0; 15.78 GiB total capacity; 7.43 GiB already allocated; 6.96 GiB free; 7.53 GiB reserved in total by PyTorch)`

Any update on this?

**Comment by jp-krow** [comment]
FIXED, opening PR

**Comment by Sleepychord** [comment]
@jp-krow Hi, I have read your pull request, but still do not know the reason. Why loading weights to CPU "reducing" main memory consumption? I just experimented on my servers and did not observe this phenomenon.  Could you provides more details?

**Comment by fuzzbuck** [comment]
> 
> 
> @jp-krow Hi, I have read your pull request, but still do not know the reason. Why loading weights to CPU "reducing" main memory consumption? I just experimented on my servers and did not observe this phenomenon. Could you provides more details?

we are not 100% sure either, but I assume it's because of some internal duplication within pytorch when loading directly into cuda.

GPT-J (https://github.com/kingoflolz/mesh-transformer-jax) had a similar problem and it was solved by this as well

Have you tried the text2image script on a GPU with 16 GB vRAM?

**Comment by Sleepychord** [comment]
@fuzzbuck Thank you for your testing. I tracked the memory usage when loading, and the two methods are basically the same. By the way, GPT-J does not use pytorch, so it is not the same problem. I suspect the reason is the resource of colab is assigned at random. A single 16GB V100 and very small main memory cannot run the model. 
I will appreciate it if you can have more details, but I cannot merge the pull request at this moment.

**Comment by fuzzbuck** [comment]
> 
> 
> @fuzzbuck Thank you for your testing. I tracked the memory usage when loading, and the two methods are basically the same. By the way, GPT-J does not use pytorch, so it is not the same problem. I suspect the reason is the resource of colab is assigned at random. A single 16GB V100 and very small main memory cannot run the model.
> I will appreciate it if you can have more details, but I cannot merge the pull request at this moment.

(when refering to GPT-J, I meant the HuggingFace pytorch port)
I think it's about the .half() call before converting it to cuda
Can you try the following snippet?

`
checkpoint = torch.load(path, map_location=torch.device('cpu'))
model.load_state_dict(checkpoint["module"])
model = model.half().cuda()       
`

**Comment by Sleepychord** [comment]
@fuzzbuck @jp-krow I see! It is indeed caused by duplication. I was confused by the first report of Out-of-RAM, but I now know you are wanting to load it on a 16GB GPU. 
I find that directly load the checkpoints on CPU has no obvious drawback, so adding an argument is not needed. I have fixed it.
Thank you for your comments.
